# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenVe < Formula
  desc "Open-VE: A powerful solution that simplifies the management of validation rules, ensuring consistent validation across all layers, including frontend, BFF, and microservices, through a single, simple API."
  homepage ""
  version "1.4-alpha"

  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/shibukazu/open-ve/releases/download/v1.4-alpha/open-ve_Darwin_x86_64.tar.gz"
      sha256 "0594ee8b3b348c988288b9a67c0e0462f6cb20f48edcb14be8617f99f9aacc07"

      def install
        bin.install "open-ve"
      end
    end
    on_arm do
      url "https://github.com/shibukazu/open-ve/releases/download/v1.4-alpha/open-ve_Darwin_arm64.tar.gz"
      sha256 "09c4e4686e2efa984e4d5af6d437f1a92466a95f0456bad1759506a6a42363e7"

      def install
        bin.install "open-ve"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibukazu/open-ve/releases/download/v1.4-alpha/open-ve_Linux_x86_64.tar.gz"
        sha256 "d5a37aa9fc57978536c2fb33b0b2128f0d45d566277addd392d0eaa23e39564c"

        def install
          bin.install "open-ve"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibukazu/open-ve/releases/download/v1.4-alpha/open-ve_Linux_arm64.tar.gz"
        sha256 "1f128903447aed7e68b87ff7ba10fcadb85c5e24b416da89bcb8a0cd55dc2649"

        def install
          bin.install "open-ve"
        end
      end
    end
  end
end
