# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenVe < Formula
  desc "Open-VE: A powerful solution that simplifies the management of validation rules, ensuring consistent validation across all layers, including frontend, BFF, and microservices, through a single, simple API."
  homepage ""
  version "1.1-alpha"

  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/shibukazu/open-ve/releases/download/v1.1-alpha/open-ve_Darwin_x86_64.tar.gz"
      sha256 "7e864567c30d22e5a702a44c19a0e899fb6aad9c8d192a4840c2ff3dd3a560fb"

      def install
        bin.install "open-ve"
      end
    end
    on_arm do
      url "https://github.com/shibukazu/open-ve/releases/download/v1.1-alpha/open-ve_Darwin_arm64.tar.gz"
      sha256 "6fcc9838a2ba1ebd07c2ba80fc6b81ec4dd88c9de9ef82f7f7e924597eeff947"

      def install
        bin.install "open-ve"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibukazu/open-ve/releases/download/v1.1-alpha/open-ve_Linux_x86_64.tar.gz"
        sha256 "b9619ab722cd924ab6ebd857db1479b7c13e802a94503d8988a18ad3368bcdc1"

        def install
          bin.install "open-ve"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibukazu/open-ve/releases/download/v1.1-alpha/open-ve_Linux_arm64.tar.gz"
        sha256 "58d49df0a4b60f72db7d7fca2f517f267f859ee91f69b3c685b20f38fe221cf1"

        def install
          bin.install "open-ve"
        end
      end
    end
  end
end
